import Head from 'next/head'
import NavBar from '../components/NavBar'
import axios from 'axios'
import CustomForm from '../components/CustomForm'
import { useContext, useEffect, useState } from 'react'
import { Button } from 'flowbite-react'
import { useRouter } from 'next/router'
import { authContext } from '../context/AuthContext'
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'


const MySwal = withReactContent(Swal)

const initialState = {
  id: "",
  nombre: "",
  apellido: "",
  correo: "",
  contrasena: "",
  contrasena2: "",
}

export default function Register() {
  const router = useRouter()
  const [infoRegister, setInfoRegister] = useState(initialState)
  const { login } = useContext(authContext);
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    (async () => {
      let user = JSON.parse(localStorage.getItem('session'))
      if (user) {
        login(user)
        await router.push('/')
      }
      setLoading(false)
    })()
  }, [])

  const fields = [
    {
      id: 'id',
      name: 'id',
      label: 'ID',
      value: infoRegister.id,
      onChange: (e) => setInfoRegister({ ...infoRegister, id: e.target.value }),
      placeholder: 'Ingrese su ID'
    },
    {
      id: 'nombre',
      name: 'nombre',
      label: 'Nombre',
      value: infoRegister.nombre,
      onChange: (e) => setInfoRegister({ ...infoRegister, nombre: e.target.value }),
      placeholder: 'Ingrese su nombre',
    },
    {
      id: 'apellido',
      name: 'apellido',
      label: 'Apellido',
      value: infoRegister.apellido,
      onChange: (e) => setInfoRegister({ ...infoRegister, apellido: e.target.value }),
      placeholder: 'Ingrese su apellido',
    },
    {
      id: 'correo',
      name: 'correo',
      label: 'Correo',
      value: infoRegister.correo,
      onChange: (e) => setInfoRegister({ ...infoRegister, correo: e.target.value }),
      placeholder: 'Ingrese su correo',
      type: 'email',
    },
    {
      id: 'contrasena',
      name: 'contrasena',
      label: 'Contraseña',
      value: infoRegister.contrasena,
      onChange: (e) => setInfoRegister({ ...infoRegister, contrasena: e.target.value }),
      type: 'password',
      placeholder: 'Ingrese su contraseña',
    },
    {
      id: 'constrasena2',
      name: 'constrasena2',
      label: 'Confirmar Contraseña',
      value: infoRegister.contrasena2,
      onChange: (e) => setInfoRegister({ ...infoRegister, contrasena2: e.target.value }),
      type: 'password',
      placeholder: 'Confirme su contraseña',
    }
  ]

  const handleSubmit = async (e) => {
    e.preventDefault()
    try {
      const response = await axios.post('/api/auth/registro', infoRegister)
      const { data } = response
      if (data.ok) {
        MySwal.fire({
          title: 'Registro Exitoso',
          text: `Ya puede iniciar sesión`,
          icon: 'success',
          confirmButtonText: 'Ok'
        }).then(() => {
          router.push('/login')
        })
      }
    } catch (error) {
      const { response } = error
      if (response.status >= 400 && response.status < 500) {
        MySwal.fire({
          title: 'Error',
          text: response.data.message,
          icon: 'error',
          confirmButtonText: 'Ok'
        })
      } else if (response.status === 500) {
        MySwal.fire({
          title: 'Error',
          text: 'Error en el servidor',
          icon: 'error',
          confirmButtonText: 'Ok'
        })
      }
    }
  }

  if (loading) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>Registro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="h-[calc(100vh-64px)] overflow-y-auto">
        <section className="flex flex-col w-1/2 m-auto my-10">
          <h2 className="text-center text-2xl">Registro</h2>
          <CustomForm
            fields={fields}
            onSubmit={handleSubmit}
            btnLabel="Registrarse"
          />
          <Button
            size="xs"
            type="button"
            onClick={() => router.push('/login')}
          >
            Inicar Sesión
          </Button>
        </section>
      </main>
    </>
  )
}
